#!/usr/bin/env python3
"""
phi_miner.py — Symbolic Regression Engine for Discovering φ‑Coherent Mathematics from CUDA Code

Given a CUDA kernel source, this tool:
1. Extracts tunable parameters (tile sizes, unroll factors, etc.)
2. Generates and compiles kernel variants across a combinatorial parameter grid
3. Profiles each variant to measure performance (TFLOPS, latency, occupancy)
4. Performs symbolic regression to find mathematical expressions relating parameters to performance
5. Scores expressions by their "φ‑coherence" — presence of golden ratio, Fibonacci numbers, etc.
6. Outputs a ranked list of discovered formulas.

Usage:
    python phi_miner.py --kernel path/to/kernel.cu --param-grid grid.json --output formulas.json
"""

import os
import re
import ast
import json
import math
import random
import shutil
import hashlib
import tempfile
import subprocess
import itertools
from typing import List, Dict, Tuple, Any, Optional, Callable
from dataclasses import dataclass, field
from collections import defaultdict
import numpy as np
from scipy.optimize import curve_fit

# ============================================================================
# Golden Ratio & Fibonacci Utilities
# ============================================================================
PHI = (1 + math.sqrt(5)) / 2
PHI_INV = 1 / PHI
FIB = [1, 2, 3, 5, 8, 13, 21, 34, 55, 89, 144, 233, 377, 610, 987, 1597]

def phi_score(expr_str: str) -> float:
    """Score an expression string for φ‑coherence based on presence of golden ratio, Fibonacci numbers."""
    score = 0.0
    # Check for explicit φ / phi
    if 'phi' in expr_str.lower() or 'φ' in expr_str or '1.618' in expr_str:
        score += 10.0
    # Check for Fibonacci numbers
    for f in FIB:
        if str(f) in expr_str:
            score += 1.0
    # Check for inverse φ
    if '0.618' in expr_str:
        score += 5.0
    # Complexity penalty (prefer simpler expressions)
    score -= 0.1 * len(expr_str)
    return score

# ============================================================================
# CUDA Kernel Parameter Extraction
# ============================================================================
@dataclass
class KernelParameter:
    name: str
    type: str  # 'int', 'choice', 'bool'
    default: Any
    range: List[Any]  # for int: (min,max), for choice: list of options

def extract_parameters(kernel_source: str) -> List[KernelParameter]:
    """
    Parse CUDA kernel source to find tunable parameters.
    Looks for common patterns:
    - constexpr int TILE_K = 64;
    - #define UNROLL_FACTOR 4
    - template<int BLOCK_M> 
    """
    params = []
    # Find constexpr int definitions
    constexpr_pattern = re.compile(r'constexpr\s+int\s+(\w+)\s*=\s*(\d+);')
    for match in constexpr_pattern.finditer(kernel_source):
        name = match.group(1)
        default = int(match.group(2))
        # Provide a reasonable range around default
        min_val = max(1, default // 2)
        max_val = default * 2
        # Restrict to Fibonacci numbers if possible
        fib_range = [f for f in FIB if min_val <= f <= max_val]
        if fib_range:
            rng = fib_range
        else:
            rng = list(range(min_val, max_val+1, max(1, (max_val-min_val)//5)))
        params.append(KernelParameter(name=name, type='int', default=default, range=rng))
    
    # Find template parameters
    template_pattern = re.compile(r'template\s*<\s*int\s+(\w+)\s*>')
    for match in template_pattern.finditer(kernel_source):
        name = match.group(1)
        # Common template param names suggest tile sizes
        if 'BLOCK' in name or 'TILE' in name:
            params.append(KernelParameter(name=name, type='int', default=128, range=[32,64,128,256]))
    
    # Find #define macros
    define_pattern = re.compile(r'#define\s+(\w+)\s+(\d+)')
    for match in define_pattern.finditer(kernel_source):
        name = match.group(1)
        default = int(match.group(2))
        params.append(KernelParameter(name=name, type='int', default=default, range=[default//2, default, default*2]))
    
    return params

# ============================================================================
# Kernel Compilation & Profiling Harness
# ============================================================================
class CUDAProfiler:
    """Compile and profile a CUDA kernel with given parameter values."""
    def __init__(self, kernel_source: str, kernel_name: str, params: List[KernelParameter]):
        self.kernel_source = kernel_source
        self.kernel_name = kernel_name
        self.params = params
        self.temp_dir = tempfile.mkdtemp(prefix='phi_miner_')
    
    def _generate_config_header(self, values: Dict[str, Any]) -> str:
        """Generate a header file defining the parameter values."""
        lines = ['// Auto-generated by phi_miner', '#pragma once']
        for name, val in values.items():
            lines.append(f'#define {name} {val}')
        return '\n'.join(lines)
    
    def compile_and_run(self, values: Dict[str, Any]) -> Dict[str, float]:
        """
        Compile kernel with given parameter values, run a microbenchmark,
        and return performance metrics.
        """
        # In a real implementation, this would:
        # 1. Write config.h
        # 2. Invoke nvcc to compile a driver program
        # 3. Run the executable multiple times
        # 4. Parse nvprof / nsys output for metrics
        # For demonstration, we simulate with a φ‑coherent performance model.
        metrics = self._simulate_performance(values)
        return metrics
    
    def _simulate_performance(self, values: Dict[str, Any]) -> Dict[str, float]:
        """
        Simulate performance based on a hidden φ‑coherent ground truth.
        This allows testing the symbolic regression without real hardware.
        """
        # Hidden true relationship: TFLOPS = base * (1 - phi^{-occupancy}) * ...
        base_tflops = 1000.0
        # Occupancy depends on register usage and tile size
        tile_k = values.get('TILE_K', values.get('BLOCK_K', 64))
        tile_m = values.get('TILE_M', values.get('BLOCK_M', 128))
        regs = values.get('MAX_REGISTERS', 128)
        
        # True φ‑relationship: optimal occupancy = phi^2/(phi^2+phi^{-3}) * max_occupancy
        max_occ = 1.0
        actual_occ = max_occ * (PHI**2) / (PHI**2 + PHI_INV**3)
        # Add noise based on deviation from Fibonacci tile sizes
        tile_score = 1.0
        if tile_k not in FIB:
            tile_score *= 0.9
        if tile_m not in FIB:
            tile_score *= 0.9
        # Register pressure effect
        reg_factor = max(0.5, 1.0 - 0.01 * max(0, regs - 255))
        
        tflops = base_tflops * actual_occ * tile_score * reg_factor
        # Add small noise
        tflops *= np.random.normal(1.0, 0.02)
        
        latency_us = 1000.0 / tflops * 10  # arbitrary scaling
        occupancy = actual_occ * tile_score
        
        return {
            'TFLOPS': tflops,
            'latency_us': latency_us,
            'occupancy': occupancy
        }
    
    def cleanup(self):
        shutil.rmtree(self.temp_dir, ignore_errors=True)

# ============================================================================
# Symbolic Regression Engine
# ============================================================================
class SymbolicRegressor:
    """
    Genetic programming for symbolic regression.
    Evolves mathematical expressions to fit a dataset.
    """
    def __init__(self, variables: List[str], population_size: int = 200, generations: int = 20):
        self.variables = variables
        self.population_size = population_size
        self.generations = generations
        self.operators = ['+', '-', '*', '/', 'pow', 'log', 'exp', 'sqrt']
        self.constants = [str(c) for c in [0.1, 0.5, 1.0, 2.0, PHI, PHI_INV] + FIB[:5]]
        self.max_depth = 4
    
    def _random_expr(self, depth: int = 0) -> str:
        if depth >= self.max_depth or random.random() < 0.3:
            # Terminal: variable or constant
            return random.choice(self.variables + self.constants)
        op = random.choice(self.operators)
        if op in ['+', '-', '*', '/']:
            left = self._random_expr(depth+1)
            right = self._random_expr(depth+1)
            return f'({left} {op} {right})'
        else:
            arg = self._random_expr(depth+1)
            return f'{op}({arg})'
    
    def _evaluate_expr(self, expr_str: str, data_point: Dict[str, float]) -> float:
        """Safely evaluate an expression with variable bindings."""
        # Replace variable names with values
        eval_str = expr_str
        for var, val in data_point.items():
            eval_str = eval_str.replace(var, str(val))
        # Add math functions
        namespace = {
            'phi': PHI,
            'φ': PHI,
            'pow': math.pow,
            'log': math.log,
            'exp': math.exp,
            'sqrt': math.sqrt,
            'abs': abs,
            'sin': math.sin,
            'cos': math.cos
        }
        try:
            return float(eval(eval_str, {"__builtins__": {}}, namespace))
        except:
            return float('inf')
    
    def fitness(self, expr_str: str, X: List[Dict], y: List[float]) -> float:
        """Mean squared error plus φ‑coherence bonus."""
        errors = []
        for data_point, target in zip(X, y):
            pred = self._evaluate_expr(expr_str, data_point)
            if math.isinf(pred) or math.isnan(pred):
                return float('inf')
            errors.append((pred - target) ** 2)
        mse = np.mean(errors)
        # φ‑coherence bonus
        phi_bonus = phi_score(expr_str)
        # Combine: lower is better
        return mse / (1.0 + 0.1 * phi_bonus)
    
    def mutate(self, expr_str: str) -> str:
        # Simple mutation: replace a subtree
        if random.random() < 0.5:
            return self._random_expr(0)
        # Find a random operator or terminal and replace
        tokens = re.findall(r'[\w\.]+|[()+\\-*/]', expr_str)
        if not tokens:
            return expr_str
        idx = random.randint(0, len(tokens)-1)
        if tokens[idx] in self.operators:
            tokens[idx] = random.choice(self.operators)
        elif tokens[idx] in self.variables + self.constants:
            tokens[idx] = random.choice(self.variables + self.constants)
        return ''.join(tokens)
    
    def crossover(self, expr1: str, expr2: str) -> str:
        # Swap random subtrees (simplified)
        # Find a common operator and swap subtrees
        # For simplicity, just pick one randomly
        return expr1 if random.random() < 0.5 else expr2
    
    def fit(self, X: List[Dict], y: List[float], target_metric: str = 'TFLOPS') -> List[Tuple[str, float]]:
        """Run genetic programming and return top expressions with fitness."""
        population = [self._random_expr() for _ in range(self.population_size)]
        best = []
        for gen in range(self.generations):
            # Evaluate fitness
            fitnesses = [self.fitness(ind, X, y) for ind in population]
            # Keep best
            sorted_pop = sorted(zip(population, fitnesses), key=lambda x: x[1])
            best_in_gen = sorted_pop[0]
            best.append(best_in_gen)
            # Selection (tournament)
            new_pop = [best_in_gen[0]]  # elitism
            while len(new_pop) < self.population_size:
                # Tournament selection
                candidates = random.sample(list(zip(population, fitnesses)), 3)
                parent1 = min(candidates, key=lambda x: x[1])[0]
                candidates = random.sample(list(zip(population, fitnesses)), 3)
                parent2 = min(candidates, key=lambda x: x[1])[0]
                child = self.crossover(parent1, parent2)
                if random.random() < 0.3:
                    child = self.mutate(child)
                new_pop.append(child)
            population = new_pop
        
        # Return top 10 unique expressions
        unique = {}
        for expr, fit in best:
            if expr not in unique or fit < unique[expr]:
                unique[expr] = fit
        return sorted(unique.items(), key=lambda x: x[1])[:10]

# ============================================================================
# Main φ‑Miner Class
# ============================================================================
class PhiMiner:
    def __init__(self, kernel_path: str):
        with open(kernel_path, 'r') as f:
            self.source = f.read()
        self.kernel_name = os.path.splitext(os.path.basename(kernel_path))[0]
        self.params = extract_parameters(self.source)
        print(f"Extracted {len(self.params)} tunable parameters.")
    
    def generate_experiment_grid(self, max_combinations: int = 5000) -> List[Dict[str, Any]]:
        """Generate parameter combinations for experiments."""
        if not self.params:
            return [{}]
        # Use itertools.product, but limit total
        param_names = [p.name for p in self.params]
        param_values = [p.range for p in self.params]
        total = 1
        for r in param_values:
            total *= len(r)
        if total > max_combinations:
            # Subsample using φ‑sparse selection
            grid = []
            for _ in range(max_combinations):
                combo = {}
                for p in self.params:
                    # Choose Fibonacci‑indexed positions
                    idx = random.choice([i for i, _ in enumerate(p.range) if i in FIB or i < len(FIB)])
                    combo[p.name] = p.range[min(idx, len(p.range)-1)]
                grid.append(combo)
            return grid
        else:
            return [dict(zip(param_names, combo)) for combo in itertools.product(*param_values)]
    
    def run_experiments(self, grid: List[Dict]) -> Tuple[List[Dict], List[float]]:
        """Compile, run, and profile each parameter combination."""
        profiler = CUDAProfiler(self.source, self.kernel_name, self.params)
        X = []
        y = []
        print(f"Running {len(grid)} experiments...")
        for i, values in enumerate(grid):
            if i % max(1, len(grid)//10) == 0:
                print(f"  {i}/{len(grid)}")
            metrics = profiler.compile_and_run(values)
            # Use TFLOPS as target for regression
            X.append(values)
            y.append(metrics['TFLOPS'])
        profiler.cleanup()
        return X, y
    
    def mine_formulas(self) -> List[Dict[str, Any]]:
        """Run the full mining pipeline and return discovered formulas."""
        # 1. Generate experiment grid
        grid = self.generate_experiment_grid(max_combinations=1000)
        # 2. Run experiments (or load cached results)
        X, y = self.run_experiments(grid)
        # 3. Symbolic regression
        variables = list(self.params[0].keys()) if self.params else []
        regressor = SymbolicRegressor(variables, population_size=100, generations=10)
        top_exprs = regressor.fit(X, y)
        # 4. Format results
        results = []
        for expr, fitness in top_exprs:
            phi_score_val = phi_score(expr)
            results.append({
                'expression': expr,
                'mse': fitness,
                'phi_score': phi_score_val,
                'interpretation': self._interpret(expr)
            })
        return results
    
    def _interpret(self, expr: str) -> str:
        """Provide a human-readable interpretation of the formula."""
        if 'phi' in expr.lower() and 'occupancy' in expr:
            return "Optimal occupancy involves golden ratio, suggesting a φ‑resonant warp scheduling."
        elif any(str(f) in expr for f in FIB):
            return "Contains Fibonacci numbers, indicating optimal tile sizes or strides."
        return "Formula discovered; further analysis recommended."

# ============================================================================
# CLI
# ============================================================================
def main():
    import argparse
    parser = argparse.ArgumentParser(description='φ‑Miner: Discover φ‑coherent math from CUDA code.')
    parser.add_argument('--kernel', type=str, required=True, help='Path to CUDA kernel source')
    parser.add_argument('--output', type=str, default='phi_formulas.json', help='Output JSON file')
    args = parser.parse_args()
    
    miner = PhiMiner(args.kernel)
    formulas = miner.mine_formulas()
    
    with open(args.output, 'w') as f:
        json.dump(formulas, f, indent=2)
    
    print(f"\nDiscovered {len(formulas)} φ‑coherent formulas:")
    for i, f in enumerate(formulas):
        print(f"{i+1}. {f['expression']}")
        print(f"   MSE: {f['mse']:.4f}, φ‑score: {f['phi_score']:.1f}")
        print(f"   {f['interpretation']}\n")
    
    print(f"Results saved to {args.output}")

if __name__ == "__main__":
    main()
